### ISSUE TITLE
install Anaconda2 and reinstall Spyder

### ISSUE THREAD

**Issue by qds007** [qds007/qds#24]
any command prompt can run pip install ( path set already)
spyder project file, how to add existing .py file and directory

**Comment by squidding007** [comment]
Read these instructions
https://python-packaging.readthedocs.io/en/latest/

**Comment by squidding007** [comment]
Environments with python 2.7 vs. 3.5 (last I heard this did not work)
https://conda.io/docs/py2or3.html#create-a-python-2-7-environment

**Comment by qds007** [comment]
it looks like data science is moving towards 3
and now the major packages are compatible

So this issue is closed
