### ISSUE TITLE
Data Structures in C

### ISSUE THREAD

**Issue by squidding007** [qds007/qds#25]
Binary Search Tree,
Hash Table,
Trie

Why do these exist and how are they used

**Comment by qds007** [comment]
List<int> list= new List<int>();
            string s = "1";
            long hc = list.GetHashCode();

            Console.WriteLine(hc);
https://en.wikipedia.org/wiki/Hash_table

**Comment by qds007** [comment]
https://en.wikipedia.org/wiki/Binary_search_tree
https://msdn.microsoft.com/en-us/library/ms379572(v=vs.80).aspx

**Comment by qds007** [comment]
https://en.wikipedia.org/wiki/Trie
https://visualstudiomagazine.com/articles/2015/10/20/text-pattern-search-trie-class-net.aspx
