### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by squidding007** [qds007/qds#27]
Actually, did some background research and https://www.quora.com/Which-version-of-Python-is-more-often-used-in-machine-learning-Python-2-7-or-Python-3-0+

As of May 2017, most machine learning packages (Sklearn, Keras, XGBoost) are now compatible with Python 3.5. So I will switch to 

Python 3.5
Anaconda 3

**Comment by qds007** [comment]
adding files to Spyder is supported after Aug 2016, 3.0+
https://github.com/spyder-ide/spyder/issues/3099
Our new projects are attached to a directory, so you need to add files to a project, you just add them to the directory.
select the top most your package directory to be the root of your project to include your python dir/files as a package

**Comment by squidding007** [comment]
Key syntax differences between Python 2 and 3: http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html

**Comment by squidding007** [comment]
Downloaded new anaconda, learning syntax differences. Close Issue
