### ISSUE TITLE
Verify math on driving, housing and efficiency

### ISSUE THREAD

**Issue by qds007** [qds007/qds#29]
http://www.brooklinedriving.com/prices.htm
$435 to achieve 95%, estimate risk of failing test- strategic vs. scientific thinking, effective personality
Distance low cost living vs. speed up upward movement, Motivation and health
Combined new life style--Total Cost estimate, max goal, living system need a goal, profession vs. social
effective and efficient -- Parallel learning tasks CEL, Academic vs. Data Scientist vs. Strategic Thinking vs. QR, dual monitors
Next target and prepare for GMAT, try out real GMAT not sample in pamphlet

**Comment by qds007** [comment]
https://www.apartments.com/mass-place-washington-dc/0h3kvj0/

**Comment by squidding007** [comment]
This is affordable and nice but a bit far away from work (45 min subway)

**Comment by qds007** [comment]
https://www.yelp.com/search?cflt=driving_schools&find_loc=Boston%2C+MA

**Comment by qds007** [comment]
Zillow $259k 1Bd, init cost 5% =$13k, Mort $1000/month, Tax 3500,/year, HOA Fee (est) 300/month
Total Per month cost est. = 1000+ 300+300=1600.
Must sell profit = $280K to break even
