### ISSUE TITLE
Measure strategic and management thinking: GMAT 

### ISSUE THREAD

**Issue by qds007** [qds007/qds#34]
https://www.4tests.com/gmat
http://gmat.babson.edu/  (Full Test and detailed analysis of your performance)
http://gmat.london.edu/

**Comment by squidding007** [comment]
![screenshot 2](https://user-images.githubusercontent.com/22949239/27557041-121d68e4-5a86-11e7-8298-7481362b2745.png)

**Comment by squidding007** [comment]
Not sure how the predicted score is calculated. I got a few wrong in math due to unfamiliar questions, but verbal was fine.

**Comment by qds007** [comment]
Cool, you know your skill level may come handy
