### ISSUE TITLE
Driving Lessons

### ISSUE THREAD

**Issue by squidding007** [qds007/qds#41]
Normal Lesson means you get picked up by the previous student and you pick up the next student. Private Lesson means that the instructor picks you up. You are still driving for the full lesson. 

Earliest road test is still August 5th, Brookline High School. 
Payment is by Credit Card over the phone, or in person with check. 
Pickup near Cleveland Circle in Brookline (on Green Line)

**Comment by qds007** [comment]
Pay credit card, safer, protected against fraud, cash back 2%
Go to clev circle 5 times not bad
5th good, apartment start 9/1 or August 20
